version: '2'
services:
  web:
    build: .
    command: npm run start
    volumes:
      - .:/usr/app/memoriz/
      - /usr/app/memoriz/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: memoriz
      MYSQL_DATABASE: memoriz
      MYSQL_USER: memoriz
      MYSQL_PASSWORD: memoriz

  db_admin:
    image: adminer
    links:
      - db
    ports:
      - 8081:8080

volumes:
  mysql_data_memoriz: {}
