version: '2'
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/memoriz/
      - /usr/app/memoriz/node_modules
    environment:
      POSTGRES_DB: memoriz
      POSTGRES_USER: memoriz
      POSTGRES_PASSWORD: memoriz
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data_memoriz:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: memoriz
      POSTGRES_USER: memoriz
      POSTGRES_PASSWORD: memoriz
    ports:
      - "5432:5432"

  db_admin:
    image: adminer
    links:
      - db
    ports:
      - 8081:8080

volumes:
  postgres_data_memoriz: {}
